---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - tree.nullcloud.io
  resources:
  - trees
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tree.nullcloud.io
  resources:
  - trees/finalizers
  verbs:
  - update
- apiGroups:
  - tree.nullcloud.io
  resources:
  - trees/status
  verbs:
  - get
  - patch
  - update
