# This rule is not used by the project tree-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the tree.nullcloud.io.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: tree-operator
    app.kubernetes.io/managed-by: kustomize
  name: tree-editor-role
rules:
- apiGroups:
  - tree.nullcloud.io
  resources:
  - trees
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tree.nullcloud.io
  resources:
  - trees/status
  verbs:
  - get
